### ISSUE TITLE
CrossOver expired.

### ISSUE THREAD

**Issue by laurentbastien** [Zuzzuc/Battlefield-1942-installer#2] opened 2018-05-30 15:27 UTC
Here's what I'm seeing after running Battlefield 1942.iso:

https://imgur.com/a/hSXmSsU

I can't run either autorun.exe or setup.exe because apparently my trial version of CrossOver has expired.

**Comment by Zuzzuc** [comment] 2018-05-30 16:55
This script does not install CrossOver, it uses wine. Is it possible that you installed CrossOver in the past? 

Try to uninstall crossover and install wine( can’t find exact link atm as I’m on vacation) and try to run the install script again! 

If that works, please tell me so I can close the issue.

**Comment by laurentbastien** [comment] 2018-05-30 20:23
Okay, it works now. I'm at the installer and they're prompting me to insert disk 2.

**Comment by Zuzzuc** [comment] 2018-05-30 20:31
The script is supposedly to download a pre installed package, meaning the game is supposed to be playable immediately after the script finishes. Something probably went wrong during the installation phase. Remove all files with this command: rm -rf $HOME/Documents/Battlefield\ 1942.iso /tmp/bf1942installer $HOME/Wine\ Files

And then run the installation script again, and everything should work!

**Comment by laurentbastien** [comment] 2018-05-30 20:59
Still not working. I've removed the file, ran the installation again, and launching "Battlefield Launcher.command" in wine still prompts me to install the game by inserting CDs.

**Comment by Zuzzuc** [comment] 2018-05-31 04:24
I went and dug a bit deeper on why this happend, it appears that the problem is caused by the server. The pre installed files never gets sent by the server.

Unfortunately that means I can’t fix it from my mobile phone, and it will take at least two weeks until I’m home. I’ll inform you when the problem is solved!

**Comment by Zuzzuc** [comment] 2018-06-15 21:34
The problem should be solved now!

**Closed as completed by Zuzzuc** 2018-06-15 21:34 UTC
